functionality:
  name: "parse_imhex"
  namespace: "civ6_save_renderer"
  version: "main_build"
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Specify the input file to be parsed."
    example:
    - "input.bin"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--pattern"
    alternatives:
    - "-p"
    description: "Specify the imhex file (.hex) to be used for parsing."
    example:
    - "pattern.hex"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--includes"
    description: "Specify one or more directories containing imhex patterns (.imhex)\
      \ to be included as libraries."
    example:
    - "dir"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ":"
    dest: "par"
  - type: "boolean_true"
    name: "--include_imhex_patterns"
    description: "Whether to include the standard patterns from the ImHex-Patterns\
      \ repository"
    direction: "input"
    dest: "par"
  - type: "string"
    name: "--format"
    alternatives:
    - "-f"
    description: "Specify the output format for the parsed data."
    example:
    - "dir"
    required: false
    choices:
    - "json"
    - "yaml"
    - "html"
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    description: "Specify the output file for the parsed data."
    example:
    - "output.json"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "This functionality uses an ImHex format (.hex) to parse a binary file\
    \ into a JSON format."
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ubuntu:22.04"
  target_organization: "viash-io/civ6_pipeline"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/viash-io/civ6_pipeline"
  setup:
  - type: "apt"
    packages:
    - "build-essential"
    - "gcc-12"
    - "g++-12"
    - "lld"
    - "cmake"
    - "make"
    - "git"
    interactive: false
  - type: "docker"
    run:
    - "git clone --depth 1 --recurse-submodules --shallow-submodules https://github.com/WerWolv/PatternLanguage.git\
      \ /opt/PatternLanguage && \\\n  cd /opt/PatternLanguage/ && \\\n  mkdir -p build\
      \ && \\\n  cd build && \\\n  CC=gcc-12 CXX=g++-12 cmake                \\\n\
      \    -DCMAKE_BUILD_TYPE=Debug                \\\n    -DCMAKE_INSTALL_PREFIX=\"\
      /usr\"           \\\n    -DCMAKE_C_FLAGS=\"-fuse-ld=lld\"          \\\n    -DCMAKE_CXX_FLAGS=\"\
      -fuse-ld=lld\"        \\\n    -DLIBPL_ENABLE_TESTS=OFF                \\\n \
      \   -DLIBPL_ENABLE_CLI=ON                   \\\n    .. && \\\n  make install\n"
  - type: "docker"
    run:
    - "git clone --depth 1 https://github.com/WerWolv/ImHex-Patterns.git /opt/ImHex-Patterns\n"
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
- type: "native"
  id: "native"
info:
  config: "/home/runner/work/civ6_pipeline/civ6_pipeline/src/civ6_save_renderer/parse_imhex/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/civ6_pipeline/civ6_pipeline/target/nextflow/civ6_save_renderer/parse_imhex"
  executable: "/home/runner/work/civ6_pipeline/civ6_pipeline/target/nextflow/civ6_save_renderer/parse_imhex/parse_imhex"
  viash_version: "0.7.3"
  git_commit: "df76affd4a768368f1d6520838b49a03afeda77e"
  git_remote: "https://github.com/viash-io/civ6_pipeline"
