functionality:
  name: "parse_imhex"
  namespace: "civ6_save_renderer"
  version: "main_build"
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Input file"
    example:
    - "input.bin"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--pattern"
    alternatives:
    - "-p"
    description: "Pattern file"
    example:
    - "pattern.hexpat"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--includes"
    description: "Include dir"
    example:
    - "dir"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--format"
    alternatives:
    - "-f"
    description: "Format (json, yaml, html)"
    example:
    - "dir"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    description: "Output file"
    example:
    - "output.txt"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "..."
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ubuntu:22.04"
  target_organization: "viash-io/civ6_pipeline"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/viash-io/civ6_pipeline"
  setup:
  - type: "apt"
    packages:
    - "build-essential"
    - "gcc-12"
    - "g++-12"
    - "lld"
    - "cmake"
    - "make"
    - "git"
    interactive: false
  - type: "docker"
    run:
    - "git clone --recurse-submodules https://github.com/WerWolv/PatternLanguage.git\
      \ && \\\n  mkdir -p PatternLanguage/build && \\\n  cd PatternLanguage/build\
      \ && \\\n  CC=gcc-12 CXX=g++-12 cmake                \\\n    -DCMAKE_BUILD_TYPE=Debug\
      \                \\\n    -DCMAKE_INSTALL_PREFIX=\"/usr\"           \\\n    -DCMAKE_C_FLAGS=\"\
      -fuse-ld=lld\"          \\\n    -DCMAKE_CXX_FLAGS=\"-fuse-ld=lld\"        \\\
      \n    -DLIBPL_ENABLE_TESTS=OFF                \\\n    -DLIBPL_ENABLE_CLI=ON\
      \                   \\\n    .. && \\\n  make install\n"
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
- type: "native"
  id: "native"
info:
  config: "/home/runner/work/civ6_pipeline/civ6_pipeline/src/civ6_save_renderer/parse_imhex/config.vsh.yaml"
  platform: "native"
  output: "/home/runner/work/civ6_pipeline/civ6_pipeline/target/native/civ6_save_renderer/parse_imhex"
  executable: "/home/runner/work/civ6_pipeline/civ6_pipeline/target/native/civ6_save_renderer/parse_imhex/parse_imhex"
  viash_version: "0.7.3"
  git_commit: "c3661b4f97ee76d9b36d7dd8658d3db4eb19a9a9"
  git_remote: "https://github.com/viash-io/civ6_pipeline"
