functionality:
  name: civ6_report
  namespace: report
  description: Consolidate and generate final report/site
  arguments:
    - name: "--input"
      type: file
      description: "Input directory"
      required: true
      example: "docs/"
    - name: "--report"
      type: file
      description: "Output directory"
      required: true
      example: "report"
      direction: output
  resources:
    - type: bash_script
      path: ./code.sh
    - type: file
      path: mkdocs.yml
    - type: file
      path: docs
platforms:
  - type: docker
    image: dragonflyscience/quarto:2023-05-22
  - type: nextflow
    auto:
      publish: true
