functionality:
  name: parse_imhex
  namespace: civ6_save_renderer
  description: "This functionality uses an ImHex format (.hex) to parse a binary file into a JSON format."
  arguments:
    - name: "--input"
      alternatives: [-i]
      type: file
      required: true
      example: "input.bin"
      must_exist: true
      description: "Specify the input file to be parsed."
    - name: "--pattern"
      alternatives: [-p]
      type: file
      required: true
      example: "pattern.hex"
      must_exist: true
      description: "Specify the imhex file (.hex) to be used for parsing."
    - name: "--includes"
      type: file
      example: "dir"
      must_exist: true
      description: "Specify one or more directories containing imhex patterns (.imhex) to be included as libraries."
      multiple: true
    - name: "--include_imhex_patterns"
      type: boolean_true
      description: "Whether to include the standard patterns from the ImHex-Patterns repository"
    - name: "--format"
      alternatives: [-f]
      type: string
      example: "dir"
      description: "Specify the output format for the parsed data."
      choices: [json, yaml, html]
    - name: "--output"
      alternatives: [-o]
      type: file
      required: true
      example: "output.json"
      direction: output
      description: "Specify the output file for the parsed data."
  resources:
    - type: bash_script
      path: script.sh
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      # copied the build procedure from the PatternLanguage CI tests
      - type: apt
        packages: [build-essential, gcc-12, g++-12, lld, cmake, make, git]
      - type: docker  
        run: |
          git clone --depth 1 --recurse-submodules --shallow-submodules https://github.com/WerWolv/PatternLanguage.git /opt/PatternLanguage && \
            cd /opt/PatternLanguage/ && \
            mkdir -p build && \
            cd build && \
            CC=gcc-12 CXX=g++-12 cmake                \
              -DCMAKE_BUILD_TYPE=Debug                \
              -DCMAKE_INSTALL_PREFIX="/usr"           \
              -DCMAKE_C_FLAGS="-fuse-ld=lld"          \
              -DCMAKE_CXX_FLAGS="-fuse-ld=lld"        \
              -DLIBPL_ENABLE_TESTS=OFF                \
              -DLIBPL_ENABLE_CLI=ON                   \
              .. && \
            make install
      - type: docker
        run: |
          git clone --depth 1 https://github.com/WerWolv/ImHex-Patterns.git /opt/ImHex-Patterns
  - type: nextflow
  - type: native
